# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: /mnt/DataDrive246/gaofeng/Datasets/ntu120_2people/xsub/val_data_bone.npy
  label_path: /mnt/DataDrive246/gaofeng/Datasets/ntu120_2people/xsub/val_label.pkl
  debug: False

# model
model: model.MIGCN8668_CtrTemporal.Model
model_args:
  num_class: 26
  num_point: 25
  num_person: 2

  graph: graph.mirror_graph.TwoGraph

  graph_args:
    labeling_mode: 'spatial'

# test
phase: test
device: [0,1]
test_batch_size: 256
weights: /mnt/DataDrive246/gaofeng/Action Recognition Code/two_man_interaction/runs/newww/120sub_bone2-47-39216.pt
work_dir: ./work_dir/fusion
model_saved_name: ./runs/fusion
save_score: True
