work_dir: ./work_dir/newww/120setup_bone2
model_saved_name: ./runs/newww/120setup_bone2
exp_comments: 骨骼实验
#weights: /mnt/DataDrive246/gaofeng/Action Recognition Code/two_man_interaction/runs/newww/120sub-47-39216.pt
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /mnt/DataDrive246/gaofeng/Datasets/ntu120_2people/xsetup/train_data_bone.npy
  label_path: /mnt/DataDrive246/gaofeng/Datasets/ntu120_2people/xsetup/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: /mnt/DataDrive246/gaofeng/Datasets/ntu120_2people/xsetup/val_data_bone.npy
  label_path: /mnt/DataDrive246/gaofeng/Datasets/ntu120_2people/xsetup/val_label.pkl

# model
model: model.AIGCN.Model
model_args:
  num_class: 26
  num_point: 25
  num_person: 2
  graph: graph.mirror_graph.TwoGraph
  graph_args:
    labeling_mode: 'spatial'


#optim
weight_decay: 0.0004
base_lr: 0.1
step: [35, 45, 55]

# training
device: [0,1]
batch_size: 16
test_batch_size: 16
start_epoch: 0
num_epoch: 60
nesterov: True
num_worker: 0
